# Generated by Django 4.2.2 on 2023-06-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_question_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
