SELECT ROWNUM, NAME, score FROM
(SELECT ROWNUM, NAME, score
FROM Ex_SCORE
ORDER BY score DESC)
WHERE ROWNUM <=5
;

CREATE TABLE JOB_INFO(
    JOB_ID VARCHAR(10),
    MIN_SALARY NUMBER,
    MAX_SALARY NUMBER
);

INSERT INTO JOB_INFO VALUES ('AD_PRES', 20080, 40000);
INSERT INTO JOB_INFO VALUES ('AD_VP', 15000, 30000);
INSERT INTO JOB_INFO VALUES ('AD_ASST', 3000, 10000);
INSERT INTO JOB_INFO VALUES ('FI_MGR', 8200, 20000);
INSERT INTO JOB_INFO VALUES ('FI_ACCOUNT', 12280, 30000);
INSERT INTO JOB_INFO VALUES ('AC_MGR', 4500, 40000);
INSERT INTO JOB_INFO VALUES ('AC_ACCOUNT', 17000, 50000);

commit;

select * from job_info;
--집계 함수 -count(), sum(), avg()
SELECT COUNT(*) 총개수,
    AVG (MIN_SALARY) 최저급여평균,
    AVG(MAX_SALARY) 최대급여평균
    from job_info;
    
    --최저급여가 5000달러 이상인 직업이름을 검색
    
SELECT JOB_ID, MIN_SALARY from job_info
WHERE MIN_SALARY >= 5000;

CREATE VIEW V_JOB_INFO
AS SELECT *
from job_info
WHERE MIN_SALARY >= 5000;

SELECT * FROM  V_JOB_INFO;

SELECT count(*) FROM  V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY > 8000;

--직업 아이디의 이름이 AD로 시작하는 자료를 검색하시오
SELECT * FROM  V_JOB_INFO
WHERE JOB_ID  LIKE 'AD%';

DROP VIEW V_JOB_INFO;

